/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardGrid: typeof import('ant-design-vue/es')['CardGrid']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AlipayOutlined: typeof import('@ant-design/icons-vue')['AlipayOutlined']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AnnouncementRibbon: typeof import('./../src/components/Notify/AnnouncementRibbon.vue')['default']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    BarChart: typeof import('./../src/components/Charts/BarChart.vue')['default']
    ConfirmTextButton: typeof import('./../src/components/Button/ConfirmTextButton.vue')['default']
    CropperModal: typeof import('./../src/components/CropperModal/index.vue')['default']
    DeleteTextButton: typeof import('./../src/components/Button/DeleteTextButton.vue')['default']
    DictBadge: typeof import('./../src/components/Dict/display/DictBadge.vue')['default']
    DictCheckboxGroup: typeof import('./../src/components/Dict/group/DictCheckboxGroup.vue')['default']
    DictRadioGroup: typeof import('./../src/components/Dict/group/DictRadioGroup.vue')['default']
    DictSelect: typeof import('./../src/components/Dict/group/DictSelect.vue')['default']
    DictTag: typeof import('./../src/components/Dict/display/DictTag.vue')['default']
    DictTagGroup: typeof import('./../src/components/Dict/display/DictTagGroup.vue')['default']
    DictText: typeof import('./../src/components/Dict/display/DictText.vue')['default']
    Editor: typeof import('./../src/components/Editor/index.vue')['default']
    IconSelector: typeof import('./../src/components/IconSelector/IconSelector.vue')['default']
    IconSelectorModal: typeof import('./../src/components/IconSelector/IconSelectorModal.vue')['default']
    LineChart: typeof import('./../src/components/Charts/LineChart.vue')['default']
    LockOutlined: typeof import('@ant-design/icons-vue')['LockOutlined']
    LogoutOutlined: typeof import('@ant-design/icons-vue')['LogoutOutlined']
    Lov: typeof import('./../src/components/Lov/Lov.vue')['default']
    LovModal: typeof import('./../src/components/Lov/LovModal.vue')['default']
    LovSearch: typeof import('./../src/components/Lov/LovSearch.vue')['default']
    MailOutlined: typeof import('@ant-design/icons-vue')['MailOutlined']
    MobileOutlined: typeof import('@ant-design/icons-vue')['MobileOutlined']
    OperationGroup: typeof import('./../src/components/Operation/OperationGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchActions: typeof import('./../src/components/Search/SearchActions.vue')['default']
    SelectLanguage: typeof import('./../src/components/SelectLanguage/index.vue')['default']
    TaobaoOutlined: typeof import('@ant-design/icons-vue')['TaobaoOutlined']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
    WeiboOutlined: typeof import('@ant-design/icons-vue')['WeiboOutlined']
  }
}
